os: linux
dist: focal
language: java
jdk:
  - openjdk8

addons:
  apt:
    packages:
      - maven

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS sparta_dev;'
  - mysql -e 'create user 'spartauser'@'localhost' identified by 'password';'
  - mysql -e 'grant all on sparta_dev.* to 'spartauser'@'localhost';'

script:
  ./build.sh

branches:
  only:
    - main
    - dev
    - /^Sparta-.*$/
    - /^refactor/*$/
    - /^fix/*$/

notifications:
  email: false