os: linux
dist: bionic
language: java

addons:
  apt:
    packages:
      - maven
      - openjdk-8-jdk
  sonarcloud:
    organization: "randomuserik"
    token:
      secure: "H4bqWce0kM+O5/DJUG20Pw18iwZIBnQirsNwRPYwWMLiINLRFQrHlh5iQ6oCbVEZiqFT2/5lNHt0LzduqIV43bOICr2SYVUkb/FNMAVywBQzldpNkBx07K0NOVTBDLkNGzSTb3bf53Kz6gfTlUM7v7/1lRTMIe324Ru6PH6+OF2qVLM9q5iR5xA7t6GSZw4jaEPA62OiRYhnEWSURTQn7UX5Bb64REj2tD15i5mJxdswZwEpX012XTA6X9zrUuGx1ZF71gbAujoWh7FWsIh9dIcW5fTheJ9eVBPNSE4Ls5xQ88kDytec36wv3QT8iEWDCdn9L2ak86bYB0etYptu8mcKX8StNm7n++FUTj6yw1LQI71wx3WfDPRePMQbKxF/d6G0zF9GPwUmlzCSEH32fpEgIWWrrgT5sTnu+/fctbm9WwU5ne9cAtsP37D66JBrGVWPksw8QYnIOaAlWFGF2yY6/csAfKSyHI3YVi2rxJO+2LmdDsk1fIhXMNVKJHFSiFFOtRTzuXDf3C8wY32L8jrCtqipAGBPjWe1jGPFIMFn4HnRl7JbAZcxnuLkdUXIkuVOAp6eRIVQBrCwSmvNPsokOak514aPYD48JKPbgElj4oywtYuUF5soFKRPBy/a6Kufc6E/YvSIKE6lQUroij3zkX0MfCt62hQpNSAUQjc="

services:
  - mysql

before_install:
  - mysql -e "CREATE DATABASE IF NOT EXISTS hfa_dev;"
  - mysql -e "CREATE USER 'hfauser'@'localhost' IDENTIFIED BY 'password';"
  - mysql -e "GRANT ALL PRIVILEGES ON hfa_dev. * TO 'hfauser'@'localhost';"

script:
  ./build.sh

branches:
  only:
    - main
    - dev
    - /^HFA-.*$/
    - /^refactor/*$/
    - /^fix/*$/

notifications:
  email: false